### ISSUE TITLE
How to process the file?

### ISSUE THREAD

**Issue by JeromeDeLeon** [Buzut/huge-uploader-nodejs#1]
In the code below:
```js
if (assembleChunks) {
    assembleChunks()
        .then(data => console.log(data));
        .catch(err => console.log(err));
}
```
I want to process the file after it has been assembled but how would I achieved that? and also, the data written in `tmp` folder doesn't have a file extension.

**Comment by JeromeDeLeon** [comment]
I managed to access the file. I was not familiar with it but seems like you could read the file in the given location. It just bothers me because it doesn't have a file extension.

**Comment by JeromeDeLeon** [comment]
Anyway I could easily solved that by passing `postParams` right?

**Comment by Buzut** [comment]
You actually can't customize the file's name in the tmp location, but as it's not intended to stay there, once you get its name, you move it wherever you ought to and give it the name you want.

The reason behind a temporary location without being able to choose a name is to avoid colisions and to make sure files are easy to reassemble. Remember that while uploading, you might have hundreds or even thouthands of part files in the temporary directory. For that reason, it's *cleaner* to consider it as a working directory only.

You move the file with the Node.js [`fs.link`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_link_existingpath_newpath_callback) function (or its [promise counterpart](https://nodejs.org/docs/latest/api/fs.html#fs_fspromises_link_existingpath_newpath) if you're bleeding edge).

As it's just linking things on the FS, there is no copying/moving involved and it takes virtually no time.

**Comment by JeromeDeLeon** [comment]
You mean the location I got after `assembleChunks` will be use to move the that file elsewhere?

**Comment by Buzut** [comment]
Sure, when you get the assembled file path, the file is yours and you move it wherever you like and give it the name you want.

You should do this because files in the `/tmp` should be cleaned from time to time, as explained in [Garbage collection](https://github.com/Buzut/huge-uploader-nodejs#garbage-collection).

Otherwise, partials from non finished uploads will indefinitely accumulate and eat up space on the FS.

```javascript
if (assembleChunks) {
    assembleChunks()
        .then((data) => {
            // here you can save text fields to db for instance
            saveToDb({ email: data.postParams.email});

            // move file
            return fsPromises.link(data.filePath, '/my-new-cool-path/file.iso');
        });
        .catch(err => console.log(err));
}
```

**Comment by JeromeDeLeon** [comment]
Thanks 😄
