### ISSUE TITLE
Rename file when uploaded

### ISSUE THREAD

**Issue by mibmae** [Buzut/huge-uploader-nodejs#12]
Hello, thanks for module.

I have a problem, i send from REACT to NODEJS server, i have the TMP files in /tmp but how can i rename the file with original name and original ext ? 

I don't found it in REQUEST .... 

Thanks a lot in advance

**Comment by Buzut** [comment]
Hi,

The file is uploaded to `tmp/` and it's not meant to stay there. When the upload is complete you need to explicitly move it (and rename if needed) where you want. If you need to keep the original name, you have to pass it as a post parameter to be able to retrieve it.

**Comment by mibmae** [comment]
Okay that's good, now i want to send a personnalised response on uploaded. How can i do that ? i tried to make a res.send after renamed file but CANNOT SET HEADERS AFTER .... 

thanks in advance ;-)
